---
title: Pendragon
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  santa-claire:
    title: Santa Claire
    output: true
  other-stories:
    title: Other stories
    output: true
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
header_pages:
- contact.md
- stories.md
- vectors.md
- rasters.md
- vtubers.md
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- tags
- tags.lock
- tags.temp
- ".git/"
